name: Create AI-based documentation
run-name: ${{ github.actor }} creates AI-based documentation
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    container:
      image: david138/ki-doc
    steps:
      - run: ki-doc --OpenAi:ActivateExtendedCodeAnalysis true --SourceDirectory . --ExportDirectory ./doc/swtkal/
